### PR TITLE
Changed to make it work with the new Android SDK and playservices-basement

### PR DESCRIPTION
**Pull request by mastef**
Added a dependency on google-playservices-basement, which in return uses the latest SDK version

### CODE REVIEW

**Comment by mastef** [comment]
Oh, also added a method to set the UserID, I guess that got auto-added to the PR

**Comment by emibap** [comment]
Thanks!

**Comment by mastef** [comment]
I didn't mean to PR the UserId method yet, as I haven't tested it on iOS back then. Using it might break right now as the ios GA lib included in this repo is outdated and doesn't provide the kGAIUserId handling yet.

What worked locally for me was to update the iOS GA lib to a newer version.

**Comment by profelis** [comment]
Can't build my project after this PR
```...debug/bin/deps/ganalytics/build/intermediates/bundles/release/aapt/AndroidManifest.xml:11:24-61: AAPT: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').```

extension-googleplayservices-basement - latest from github

**Comment by profelis** [comment]
@mastef Can you help?

**Comment by mastef** [comment]
@profelis  Check in your export directory if you can see a `./bin/deps/google-play-services-basement/res/values/values.xml` with `<integer name="google_play_services_version">9683000</integer>`

Did you run the command for Android dependency building that's in the Android section of the readme?

**Comment by mastef** [comment]
Possibly try a clean recompile

**Comment by profelis** [comment]
@mastef 
I selected/updated Android dependencies 

```
lib/extension-googleplayservices-basement/git$ ./update_dependencies.sh
Updating existing dependencies
Clearing dependencies
Adding google-play-services-ads-lite (9.8.0)
Adding google-play-services-analytics (9.8.0)
Adding google-play-services-analytics-impl (9.8.0)
Adding google-play-services-auth (9.8.0)
Adding google-play-services-base (9.8.0)
Adding google-play-services-basement (9.8.0)
Adding google-play-services-drive (9.8.0)
Adding google-play-services-games (9.8.0)
Adding google-play-services-gcm (9.8.0)
Adding google-play-services-iid (9.8.0)
Adding google-play-services-plus (9.8.0)
Writing include.xml
Done
```

And yes, I see google_play_services_version

```
$ cat google-play-services-basement/res/values/values.xml| grep google_play_services_version       
<integer name="google_play_services_version">9877000</integer>
```

**Comment by mastef** [comment]
Is that in the extension's directory or in the `export/android` directory after you build your project? Because if it's in the `export/android` directory, then android should be able to find the value, since the `res/values/values.xml` contains it and `@integer/google_play_services_version` is defined there

**Comment by mastef** [comment]
Could you `haxelib list` which versions you're on for that project?

**Comment by profelis** [comment]
this is from my export folder
```
~/dev/haxe/<projectname>/bin/android/debug/bin/deps
$ cat google-play-services-basement/res/values/values.xml | grep google_play_services_version       
<integer name="google_play_services_version">9877000</integer>
```

My haxelib https://gist.github.com/profelis/0b93075c4d7c6f55b5c23dbdd9ec9eab

**Comment by profelis** [comment]
@mastef I created simple project and get same error 

https://dl.dropboxusercontent.com/u/1036911/testActuateExample.zip

build with command `lime test android -debug -v`

**Comment by mastef** [comment]
So it might be something else - in the latest OpenFL the whole Android build process was switched from Ant to Gradle ( https://github.com/openfl/lime/pull/777 ). When I compile your project with openfl 3.6.1 it works. @player-03 do you think this could be related - any tips on what to look out for in older Android extensions so they're compatible? Especially in this case we're circumventing the whole gradle process by pulling the classes manually in https://github.com/SempaiGames/extension-googleplayservices-basement.

**Comment by player-03** [comment]
SempaiGames's libraries are designed for Ant, and I was never able to make them work with Gradle. Instead, I wrote [my own library](https://github.com/player-03/google-play-services), which works with Gradle but not Ant.

It's possible to support both the new and old build tools: import SempaiGames's library if Lime is older than version 3.1.0, and import my library if it's newer. In theory, anyway. Sadly, old versions of Lime don't let you check version numbers, so instead you'd do something like this:

```xml
<section if="android">
	<section if="openfl-legacy || openfl-next">
		<set name="google-play-services-basement" />
		<set name="google-play-services-analytics-impl" />
		<haxelib name="extension-googleplayservices-basement" />
	</section>
	
	<section unless="openfl-legacy || openfl-next">
		<!-- <set name="play-services-basement" /> -->
		<set name="google-analytics" />
		<haxelib name="google-play-services" />
	</section>
</section>
```

I commented `<set name="play-services-basement" />` because Google Analytics declares it as a dependency, which means that if you include Google Analytics, Gradle will include Basement for you. (One of Gradle's selling points is that it's good at dependency management.)

If you did need to include Basement on its own, that's how you'd do it. Not sure what good that would do, though...

**Comment by mastef** [comment]
Thanks @player-03 ! Fully agree - of course the basement libraries are there to make them available on Ant - no use to pull them for Gradle

**Comment by mastef** [comment]
@profelis Does that help in your case? Can you try @player-03's lib

**Comment by profelis** [comment]
@mastef @player-03 Thanks! My old application works again. I create [PR-4](https://github.com/emibap/GAnalytics/pull/4), please review it.

**Comment by profelis** [comment]
@mastef next issue with this PR %-( Now with iOS build, then I build my project, I see error:
```
Undefined symbols for architecture armv7:
  "_kGAIUserId", referenced from:
      ganalytics::setUserId(char const*) in libganalytics.a(f6c95b0f_GAnalytics.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

without ganalytics library all builds/works perfect


UPD:
problem was in outdated sdk, new PR with fix https://github.com/emibap/GAnalytics/pull/5 . Please review

**Comment by mastef** [comment]
Yeah, the userID change has smuggled itself in with this PR - mentioned that in https://github.com/emibap/GAnalytics/pull/3#issuecomment-272785247

**Pull request merged**
